// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: cases.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCase = `-- name: CreateCase :exec
INSERT INTO cases (
    id,
    name,
    description
) VALUES (
    $1, $2, $3
)
`

type CreateCaseParams struct {
	ID          uuid.UUID
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateCase(ctx context.Context, arg CreateCaseParams) error {
	_, err := q.db.Exec(ctx, createCase, arg.ID, arg.Name, arg.Description)
	return err
}

const findCaseByID = `-- name: FindCaseByID :one
SELECT
    id,
    name,
    description,
    created_at,
    updated_at
FROM cases
WHERE id = $1
`

func (q *Queries) FindCaseByID(ctx context.Context, id uuid.UUID) (Case, error) {
	row := q.db.QueryRow(ctx, findCaseByID, id)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCases = `-- name: ListCases :many
SELECT
    id,
    name,
    description,
    created_at,
    updated_at
FROM cases
ORDER BY created_at DESC
`

func (q *Queries) ListCases(ctx context.Context) ([]Case, error) {
	rows, err := q.db.Query(ctx, listCases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Case
	for rows.Next() {
		var i Case
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
