// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: cases.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCase = `-- name: CreateCase :exec
INSERT INTO cases (
    id,
    name,
    description
) VALUES (
    $1, $2, $3
)
`

type CreateCaseParams struct {
	ID          uuid.UUID
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateCase(ctx context.Context, arg CreateCaseParams) error {
	_, err := q.db.Exec(ctx, createCase, arg.ID, arg.Name, arg.Description)
	return err
}

const findCaseByID = `-- name: FindCaseByID :one
SELECT
    id,
    name,
    description,
    created_at,
    updated_at
FROM cases
WHERE id = $1
`

func (q *Queries) FindCaseByID(ctx context.Context, id uuid.UUID) (Case, error) {
	row := q.db.QueryRow(ctx, findCaseByID, id)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCases = `-- name: ListCases :many
SELECT
    COUNT(*) OVER()                AS total_count,
    id,
    name,
    description,
    created_at,
    updated_at
FROM cases
WHERE name ILIKE '%' || $1 || '%'
ORDER BY
CASE WHEN $2 = 'name' AND $3 = 'asc' THEN name END ASC,
    CASE WHEN $2 = 'name' AND $3 = 'desc' THEN name END DESC,

    CASE WHEN $2 = 'created_at' AND $3 = 'asc' THEN created_at END ASC,
    CASE WHEN $2 = 'created_at' AND $3 = 'desc' THEN created_at END DESC
LIMIT  $5
OFFSET $4
`

type ListCasesParams struct {
	SearchTerm pgtype.Text
	SortBy     interface{}
	SortOrder  interface{}
	SqlOffset  int32
	SqlLimit   int32
}

type ListCasesRow struct {
	TotalCount  int64
	ID          uuid.UUID
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListCases(ctx context.Context, arg ListCasesParams) ([]ListCasesRow, error) {
	rows, err := q.db.Query(ctx, listCases,
		arg.SearchTerm,
		arg.SortBy,
		arg.SortOrder,
		arg.SqlOffset,
		arg.SqlLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCasesRow
	for rows.Next() {
		var i ListCasesRow
		if err := rows.Scan(
			&i.TotalCount,
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
