// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: documents_chunks.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const listChunksByDocumentID = `-- name: ListChunksByDocumentID :many
SELECT
    id,
    document_id,
    case_id,
    content,
    chunk_index,
    token_count,
    embedding,
    created_at
FROM document_chunks
WHERE document_id = $1
ORDER BY chunk_index ASC
`

func (q *Queries) ListChunksByDocumentID(ctx context.Context, documentID uuid.UUID) ([]DocumentChunk, error) {
	rows, err := q.db.Query(ctx, listChunksByDocumentID, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentChunk
	for rows.Next() {
		var i DocumentChunk
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.CaseID,
			&i.Content,
			&i.ChunkIndex,
			&i.TokenCount,
			&i.Embedding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveDocumentChunk = `-- name: SaveDocumentChunk :exec
INSERT INTO document_chunks (
    id,
    document_id,
    case_id,
    content,
    chunk_index,
    token_count,
    embedding
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type SaveDocumentChunkParams struct {
	ID         uuid.UUID
	DocumentID uuid.UUID
	CaseID     uuid.UUID
	Content    string
	ChunkIndex int32
	TokenCount int32
	Embedding  pgvector.Vector
}

func (q *Queries) SaveDocumentChunk(ctx context.Context, arg SaveDocumentChunkParams) error {
	_, err := q.db.Exec(ctx, saveDocumentChunk,
		arg.ID,
		arg.DocumentID,
		arg.CaseID,
		arg.Content,
		arg.ChunkIndex,
		arg.TokenCount,
		arg.Embedding,
	)
	return err
}

const searchChunksByEmbedding = `-- name: SearchChunksByEmbedding :many
SELECT
    id,
    document_id,
    case_id,
    content,
    chunk_index,
    token_count,
    created_at,
    embedding <=> $2 AS distance
FROM document_chunks
WHERE case_id = $1
ORDER BY embedding <=> $2
LIMIT $3
`

type SearchChunksByEmbeddingParams struct {
	CaseID    uuid.UUID
	Embedding pgvector.Vector
	Limit     int32
}

type SearchChunksByEmbeddingRow struct {
	ID         uuid.UUID
	DocumentID uuid.UUID
	CaseID     uuid.UUID
	Content    string
	ChunkIndex int32
	TokenCount int32
	CreatedAt  pgtype.Timestamptz
	Distance   interface{}
}

func (q *Queries) SearchChunksByEmbedding(ctx context.Context, arg SearchChunksByEmbeddingParams) ([]SearchChunksByEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, searchChunksByEmbedding, arg.CaseID, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchChunksByEmbeddingRow
	for rows.Next() {
		var i SearchChunksByEmbeddingRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.CaseID,
			&i.Content,
			&i.ChunkIndex,
			&i.TokenCount,
			&i.CreatedAt,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
