// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: documents.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const findDocumentByID = `-- name: FindDocumentByID :one
SELECT
    id,
    case_id,
    file_name,
    path,
    mime_type,
    size_bytes,
    status,
    chunks_count,
    last_error,
    created_at,
    updated_at
FROM documents
WHERE id = $1
`

func (q *Queries) FindDocumentByID(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, findDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.FileName,
		&i.Path,
		&i.MimeType,
		&i.SizeBytes,
		&i.Status,
		&i.ChunksCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocumentsByCaseID = `-- name: ListDocumentsByCaseID :many
SELECT
    id,
    case_id,
    file_name,
    path,
    mime_type,
    size_bytes,
    status,
    chunks_count,
    last_error,
    created_at,
    updated_at
FROM documents
WHERE case_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDocumentsByCaseID(ctx context.Context, caseID uuid.UUID) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByCaseID, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.FileName,
			&i.Path,
			&i.MimeType,
			&i.SizeBytes,
			&i.Status,
			&i.ChunksCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveDocument = `-- name: SaveDocument :exec
INSERT INTO documents (
    id,
    case_id,
    file_name,
    path,
    mime_type,
    size_bytes,
    status,
    chunks_count,
    last_error
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type SaveDocumentParams struct {
	ID          uuid.UUID
	CaseID      uuid.UUID
	FileName    string
	Path        string
	MimeType    string
	SizeBytes   int64
	Status      int32
	ChunksCount int32
	LastError   pgtype.Text
}

func (q *Queries) SaveDocument(ctx context.Context, arg SaveDocumentParams) error {
	_, err := q.db.Exec(ctx, saveDocument,
		arg.ID,
		arg.CaseID,
		arg.FileName,
		arg.Path,
		arg.MimeType,
		arg.SizeBytes,
		arg.Status,
		arg.ChunksCount,
		arg.LastError,
	)
	return err
}

const updateDocumentChunksCount = `-- name: UpdateDocumentChunksCount :exec
UPDATE documents
SET
    chunks_count = $2,
    updated_at = now()
WHERE id = $1
`

type UpdateDocumentChunksCountParams struct {
	ID          uuid.UUID
	ChunksCount int32
}

func (q *Queries) UpdateDocumentChunksCount(ctx context.Context, arg UpdateDocumentChunksCountParams) error {
	_, err := q.db.Exec(ctx, updateDocumentChunksCount, arg.ID, arg.ChunksCount)
	return err
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :exec
UPDATE documents
SET
    status = $2,
    last_error = $3,
    updated_at = now()
WHERE id = $1
`

type UpdateDocumentStatusParams struct {
	ID        uuid.UUID
	Status    int32
	LastError pgtype.Text
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) error {
	_, err := q.db.Exec(ctx, updateDocumentStatus, arg.ID, arg.Status, arg.LastError)
	return err
}
