// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Case struct {
	ID          uuid.UUID
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Document struct {
	ID          uuid.UUID
	CaseID      uuid.UUID
	FileName    string
	Path        string
	MimeType    string
	SizeBytes   int64
	Status      int32
	ChunksCount int32
	LastError   pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type DocumentChunk struct {
	ID         uuid.UUID
	DocumentID uuid.UUID
	CaseID     uuid.UUID
	Content    string
	ChunkIndex int32
	TokenCount int32
	Embedding  pgvector.Vector
	CreatedAt  pgtype.Timestamptz
}
